import { seed } from "./core";
import { Cargo } from "../models/cargo";

export const createCargos: seed<Cargo> = {
    type: Cargo,
    data: [
        { descripc: "Jefe Informática" },
        { descripc: "ADMINISTRATIVO" },
        { descripc: "Administrativo de Inocuidad y Aseg. de Calidad" },
        { descripc: "Administrativo de Producción" },
        { descripc: "Administrativo Fábrica de Cecinas" },
        { descripc: "Administrativo Técnico de Exportaciones" },
        { descripc: "Analista Finanzas" },
        { descripc: "ASEO OPERACIONAL" },
        { descripc: "Asistente Administrativo" },
        { descripc: "Asistente Comercio Exterior" },
        { descripc: "Asistente Contable" },
        { descripc: "ASISTENTE DE FINANZAS" },
        { descripc: "Asistente de Proyecto" },
        { descripc: "Asistente Departamento Personas" },
        { descripc: "ASISTENTE DESPOSTE" },
        { descripc: "Asistente Informático" },
        { descripc: "Asistente Pañol" },
        { descripc: "Asistente Recepción y Despacho" },
        { descripc: "Atendedor de Meson" },
        { descripc: "Auxiliar / Estafeta" },
        { descripc: "Ayudante de Bodega" },
        { descripc: "CAJERA ADMINISTRATIVA" },
        { descripc: "Cajero Administrativo" },
        { descripc: "Camarero" },
        { descripc: "Chofer Repartidor" },
        { descripc: "CONTROL DE PRODUCCION" },
        { descripc: "Corredor de Ganado" },
        { descripc: "Dibujante Técnico" },
        { descripc: "Electricista" },
        { descripc: "Electrico" },
        { descripc: "Encargado Administrativo" },
        { descripc: "Encargado Bodega" },
        { descripc: "Encargado CD Paine" },
        { descripc: "Encargado de Compras" },
        { descripc: "Encargado de costos Importaciones" },
        { descripc: "Encargado de Importaciones" },
        { descripc: "Encargado Guardarropía" },
        { descripc: "Encargado Inventario" },
        { descripc: "ENCARGADO PAGO PROVEEDORES" },
        { descripc: "Encargado Pañol" },
        { descripc: "Encargado Remuneraciones" },
        { descripc: "Encargado Sala de Ventas" },
        { descripc: "Gasfiter" },
        { descripc: "INGENIERO DE PROCESOS" },
        { descripc: "Ingeniero de Servicios" },
        { descripc: "Ingeniero en Automatización y Control" },
        { descripc: "Instructor Desposte" },
        { descripc: "Jefe Administrativo" },
        { descripc: "Jefe Bodega/Insumos" },
        { descripc: "Jefe Contralor Inventario" },
        { descripc: "Jefe de Mantención" },
        { descripc: "JEFE DE RECEPCIÓN Y DESPACHO" },
        { descripc: "Jefe Departamento Prevención de Riesgos" },
        { descripc: "Jefe Distribución y Logística" },
        { descripc: "JEFE FABRICA DE CECINAS" },
        { descripc: "Jefe Faena" },
        { descripc: "Jefe Locales Camposorno" },
        { descripc: "Jefe Logística" },
        { descripc: "Jefe Sala de Ventas" },
        { descripc: "Jefe Suministros" },
        { descripc: "Laboratorista" },
        { descripc: "Lubricador" },
        { descripc: "Maestro Mayor" },
        { descripc: "Mantenimiento Estructural" },
        { descripc: "MATARIFE HALAL" },
        { descripc: "Mecanico" },
        { descripc: "Mecánico" },
        { descripc: "Mecanico Industrial" },
        { descripc: "Mecánico Soldador" },
        { descripc: "Monitor de Inocuidad y Aseg. de Calidad" },
        { descripc: "Operador Caldera" },
        { descripc: "Operador Grúa Horquilla" },
        { descripc: "Operador y Electromecánico de Operación Frio" },
        { descripc: "Operador Y Mecanico" },
        { descripc: "Operario" },
        { descripc: "Operario Aseo Industrial" },
        { descripc: "Operario de Procesos" },
        { descripc: "Operario Desposte" },
        { descripc: "Operario Elaborados" },
        { descripc: "Operario Fábrica de Cecinas" },
        { descripc: "Operario Faena" },
        { descripc: "Operario Hamburguesas" },
        { descripc: "Operario Riles /Rises" },
        { descripc: "Operario Subproducto" },
        { descripc: "Operario Subproductos" },
        { descripc: "Operario Terminal" },
        { descripc: "Operario Tráfico" },
        { descripc: "Operario Triperia" },
        { descripc: "Peoneta La Dehesa" },
        { descripc: "PLANIFICADOR DE MANTENIMIENTO" },
        { descripc: "Portero Recepcionista" },
        { descripc: "Preparador de Pedido" },
        { descripc: "Prevencionista de Riesgos" },
        { descripc: "Secretaria Gerencia" },
        { descripc: "Soldador" },
        { descripc: "SOPORTE INFORMATICO" },
        { descripc: "Supervisor" },
        { descripc: "Supervisor Aseo Industrial" },
        { descripc: "Supervisor CD Paine" },
        { descripc: "Supervisor de Cueros" },
        { descripc: "Supervisor de Despacho" },
        { descripc: "Supervisor Desposte" },
        { descripc: "Supervisor Hamburguesas" },
        { descripc: "Supervisor Inocuidad y Aseg. de Calidad Santiago" },
        { descripc: "Supervisor Recepción y Despacho" },
        { descripc: "Supervisor Riles / Rises" },
        { descripc: "Supervisor Subproductos" },
        { descripc: "Supervisor Tráfico Cajas" },
        { descripc: "Supervisor Tráfico Varas" },
        { descripc: "TECNICO EN AUTOMATIZACION Y CONTROL" },
        { descripc: "Vendedor" }
    ]
}